// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace PonziTech.BitVM.Native
{
    public static unsafe partial class BitVMNative
    {
        const string __DllName = "bitvm_ffi";





        /// <summary>
        ///  Returns the FFI version as a C string
        ///  The caller is responsible for freeing the returned pointer using bitvm_free_string()
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_ffi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* bitvm_ffi_version();

        /// <summary>
        ///  Initialize the BitVM FFI layer
        ///  Returns 0 on success, non-zero on error
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int bitvm_init();

        /// <summary>
        ///  Cleanup the BitVM FFI layer
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_cleanup", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void bitvm_cleanup();

        /// <summary>
        ///  Free a string allocated by the FFI layer
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void bitvm_free_string(byte* ptr);

        /// <summary>
        ///  Free a byte buffer allocated by the FFI layer
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_free_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void bitvm_free_bytes(byte* ptr, nuint len);

        /// <summary>
        ///  Frees a FfiResult structure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_free_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void bitvm_free_result(FfiResult result);

        /// <summary>
        ///  Execute a Bitcoin script and return the result as JSON
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_execute_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_execute_script(byte* script_bytes, nuint script_len);

        /// <summary>
        ///  Execute a script with witness inputs
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_execute_script_with_witness", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_execute_script_with_witness(byte* script_bytes, nuint script_len, byte* witness_json);

        /// <summary>
        ///  Generate a SHA256 script for the given message length
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_sha256_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_sha256_script(nuint message_len);

        /// <summary>
        ///  Generate a SHA256 script for 32-byte input
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_sha256_32bytes_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_sha256_32bytes_script();

        /// <summary>
        ///  Generate a BLAKE3 script
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_blake3_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_blake3_script(nuint message_len);

        /// <summary>
        ///  Push a u32 value onto the stack
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_u32_push_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_u32_push_script(uint value);

        /// <summary>
        ///  Generate u32 equality verification script
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bitvm_u32_equalverify_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bitvm_u32_equalverify_script();

        /// <summary>
        ///  Generate a Winternitz secret key
        ///
        ///  # Returns
        ///  FfiResult with 32 random bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "crypto_generate_winternitz_secret", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult crypto_generate_winternitz_secret();

        /// <summary>
        ///  Generate a Winternitz public key from secret
        ///
        ///  # Arguments
        ///  * `secret_bytes` - 32-byte secret key
        ///  * `secret_len` - Length of secret (must be 32)
        ///  * `message_size` - Message size in bytes (4, 16, 32, 64, or 80)
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded public key
        /// </summary>
        [DllImport(__DllName, EntryPoint = "crypto_winternitz_pubkey_from_secret", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult crypto_winternitz_pubkey_from_secret(byte* secret_bytes, nuint secret_len, uint message_size);

        /// <summary>
        ///  Sign a message with Winternitz signature
        ///
        ///  # Arguments
        ///  * `secret_bytes` - 32-byte secret key
        ///  * `secret_len` - Length of secret
        ///  * `message_bytes` - Message to sign
        ///  * `message_len` - Length of message
        ///  * `message_size` - Expected message size (4, 16, 32, 64, or 80)
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded signature
        /// </summary>
        [DllImport(__DllName, EntryPoint = "crypto_winternitz_sign", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult crypto_winternitz_sign(byte* secret_bytes, nuint secret_len, byte* message_bytes, nuint message_len, uint message_size);

        /// <summary>
        ///  Generate Winternitz signature verification script
        ///
        ///  # Arguments
        ///  * `pubkey_json` - JSON-encoded public key
        ///  * `message_size` - Message size (4, 16, 32, 64, or 80)
        ///  * `compact` - Use compact signature variant
        ///
        ///  # Returns
        ///  FfiResult with script bytecode
        /// </summary>
        [DllImport(__DllName, EntryPoint = "crypto_winternitz_checksig_script", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult crypto_winternitz_checksig_script(byte* pubkey_json, uint message_size, [MarshalAs(UnmanagedType.U1)] bool compact);

        /// <summary>
        ///  Create a depositor context
        ///
        ///  # Arguments
        ///  * `network` - Network name ("mainnet", "testnet", "signet", "regtest")
        ///  * `depositor_secret` - Depositor secret key (hex)
        ///  * `verifier_public_keys_json` - JSON array of verifier public keys (hex)
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded context on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_create_depositor_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_create_depositor_context(byte* network, byte* depositor_secret, byte* verifier_public_keys_json);

        /// <summary>
        ///  Create an operator context
        ///
        ///  # Arguments
        ///  * `network` - Network name
        ///  * `operator_secret` - Operator secret key (hex)
        ///  * `verifier_public_keys_json` - JSON array of verifier public keys
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded context on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_create_operator_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_create_operator_context(byte* network, byte* operator_secret, byte* verifier_public_keys_json);

        /// <summary>
        ///  Create a verifier context
        ///
        ///  # Arguments
        ///  * `network` - Network name
        ///  * `verifier_secret` - Verifier secret key (hex)
        ///  * `verifier_public_keys_json` - JSON array of verifier public keys (including this one)
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded context on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_create_verifier_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_create_verifier_context(byte* network, byte* verifier_secret, byte* verifier_public_keys_json);

        /// <summary>
        ///  Create a peg-in graph
        ///
        ///  # Arguments
        ///  * `context_json` - JSON-encoded depositor context
        ///  * `deposit_txid` - Deposit transaction ID (hex)
        ///  * `deposit_vout` - Deposit output index
        ///  * `deposit_amount` - Deposit amount in satoshis
        ///  * `evm_address` - Destination EVM address
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded PegInGraph on success
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_create_peg_in_graph", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_create_peg_in_graph(byte* context_json, byte* deposit_txid, uint deposit_vout, ulong deposit_amount, byte* evm_address);

        /// <summary>
        ///  Get peg-in graph status for depositor
        ///
        ///  # Arguments
        ///  * `graph_json` - JSON-encoded PegInGraph
        ///  * `esplora_url` - Esplora API URL (optional)
        ///
        ///  # Returns
        ///  FfiResult with JSON-encoded status
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_get_peg_in_depositor_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_get_peg_in_depositor_status(byte* graph_json, byte* esplora_url);

        /// <summary>
        ///  Serialize a peg-in graph to JSON
        ///
        ///  # Arguments
        ///  * `graph_json` - JSON-encoded PegInGraph
        ///
        ///  # Returns
        ///  FfiResult with normalized JSON string
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_serialize_peg_in_graph", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_serialize_peg_in_graph(byte* graph_json);

        /// <summary>
        ///  Deserialize a peg-in graph from JSON
        ///
        ///  # Arguments
        ///  * `json_data` - JSON-encoded graph data
        ///
        ///  # Returns
        ///  FfiResult with validated JSON
        /// </summary>
        [DllImport(__DllName, EntryPoint = "bridge_deserialize_peg_in_graph", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiResult bridge_deserialize_peg_in_graph(byte* json_data);


    }

    /// <summary>
    ///  Result structure for FFI operations
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        public byte* data;
        public nuint data_len;
        public byte* error_message;
    }



}
